version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: attendance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=attendance
      - DB_USER=admin
      - DB_PASSWORD=12345
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - django-network

volumes:
  postgres_data:

networks:
  django-network:
